GET http://localhost:5000/user

###

POST http://localhost:5000/user
Content-Type: application/json

{
     "name": "Rizky Perdana Nst",
     "email": "rizkyperdananst@gmail.com",
     "gender": "Male",
}